"""ACC3030 거래처계정내역 → ERP-style Excel formatter.

Reproduces the column layout, grouping, subtotals, and 거래처 합계 / 총계
rows that the ERP UI's 'Excel 변환하기' export produces. Use this so the
file generated by the playwright-cli pipeline is byte-for-byte (or close to
it) interchangeable with a human-exported workbook.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment


HEADER_36 = [
    '거래처코드', '거래처명', '회계단위코드', '회계단위명',
    '계정과목코드', '계정과목명', '승인일', '승인번호', '적요',
    '차변', '대변', '잔액', None, '전표',
    '사용부서코드', '사용부서명', '프로젝트코드', '프로젝트명',
    '관리번호', '발생일', '만기일', '요청일', '상환일',
    '환율', '외화', '이자율', '세무구분',
    '사용자정의코드', '사용자정의명', '사용자정의코드', '사용자정의명',
    '계좌번호', '예금주', '금융기관명', '작성사원코드', '작성사원명',
]


def _carry_first(r: dict) -> int:
    return 0 if '이 월' in (r.get('rmkDc') or '') else 1


def _sort_key(r: dict):
    return (
        r.get('trCd') or '',
        r.get('acctCd') or '',
        _carry_first(r),
        str(r.get('fillDt') or ''),
        str(r.get('fillNb') or ''),
        r.get('dispSq') or r.get('lnSq') or 0,
    )


def _fmt_date(yyyymmdd) -> str | None:
    s = str(yyyymmdd or '')
    if len(s) == 8 and s.isdigit():
        return f'{s[:4]}-{s[4:6]}-{s[6:]}'
    return None


def _fmt_ctnb(fillDt, fillNb, seq) -> str | None:
    if not (fillDt and fillNb is not None and seq is not None):
        return None
    try:
        seq_i = int(seq)
    except (TypeError, ValueError):
        return None
    if seq_i <= 0:
        return None
    fd = str(fillDt)
    fn = str(fillNb)
    if len(fd) != 8 or not fd.isdigit():
        return None
    return f'{fd}-{fn:>05}-{seq_i:05d}'


def _new_row() -> list:
    return [None] * 36


def _norm(v):
    """Normalize empty strings to None; keep numbers/strings."""
    return None if v == '' else v


def _data_row(r: dict, first_in_group: bool, running_balance: float, attrNm: str, divCd, divNm) -> list:
    row = _new_row()
    if first_in_group:
        row[0] = r.get('trCd')
        row[1] = attrNm
        row[2] = divCd
        row[3] = divNm
    row[4] = r.get('acctCd')
    row[5] = r.get('acctNm')
    row[6] = _fmt_date(r.get('fillDt'))
    row[7] = r.get('fillNb')
    row[8] = r.get('rmkDc')
    row[9] = r.get('drAm') or 0
    row[10] = r.get('crAm') or 0
    # idx 11 (잔액 header) stays None for data rows; idx 12 holds running balance
    row[12] = running_balance
    row[13] = _fmt_ctnb(r.get('fillDt'), r.get('fillNb'),
                        r.get('dispSq') if r.get('dispSq') is not None else r.get('lnSq'))
    row[14] = r.get('deptCd')
    row[15] = r.get('deptNm')
    row[16] = r.get('pjtCd')
    row[17] = r.get('pjtNm')
    # 18 (관리번호) / 19 (발생일) / 21 (요청일) / 22 (상환일): API doesn't expose
    row[20] = _norm(r.get('toDt'))            # 만기일
    row[23] = r.get('ctQt') or None           # 환율 (KRW=1, foreign=actual rate)
    row[24] = r.get('ctAm') or None           # 외화 (foreign currency amount)
    row[25] = 0                               # 이자율: manual fills 0 default
    # 26~30: 세무구분 / 사용자정의: API doesn't expose
    row[31] = r.get('baNb')
    row[32] = r.get('depositor')
    row[33] = r.get('bankNm')
    row[34] = r.get('empCd')
    row[35] = r.get('korNm')
    return row


def _subtotal_row(acct_nm: str, dr_sum: float, cr_sum: float) -> list:
    row = _new_row()
    row[5] = f'{acct_nm} 계'
    row[9] = dr_sum
    row[10] = cr_sum
    row[12] = 0
    return row


def _customer_total_row(name: str, dr_sum: float, cr_sum: float) -> list:
    row = _new_row()
    row[5] = f'{name} 합계'
    row[9] = dr_sum
    row[10] = cr_sum
    net = dr_sum - cr_sum
    row[11] = '차' if net >= 0 else '대'
    row[12] = abs(net)
    return row


def _grand_total_row(dr_sum: float, cr_sum: float) -> list:
    row = [''] * 36
    row[0] = '총계'
    row[9] = dr_sum
    row[10] = cr_sum
    net = dr_sum - cr_sum
    row[11] = '차' if net >= 0 else '대'
    row[12] = abs(net)
    return row


# ---------------------------------------------------------------------------
# ACC3010 거래처원장 (transaction-level) Excel formatter.
# ---------------------------------------------------------------------------

ACC3010_HEADER = [
    '날짜', '적요', '차변', '대변', '잔액',
    '거래처코드', '거래처명', '거래처분류코드', '거래처분류명',
    '적요구분', '계좌번호', '금융기관', '예금주',
    '작성일', '작성번호', '분개순번', '승인번호',
    '회계단위코드', '회계단위명', '부서코드', '부서명',
    '사원코드', '사원명', '계정과목코드', '계정과목명',
    '프로젝트코드', '프로젝트명', '사용부서코드', '사용부서명',
    '관리사원코드', '관리사원명',
]


def _acc3010_row(r: dict, running_balance: float, grp: str = '1') -> list:
    """Build one ACC3010 data row (31 columns)."""
    fd = _fmt_date(r.get('fillDt'))
    return [
        fd,                              # 0 날짜
        r.get('rmkDc'),                  # 1 적요
        r.get('acctAmDr') or 0,          # 2 차변
        r.get('acctAmCr') or 0,          # 3 대변
        running_balance,                  # 4 잔액
        r.get('trCd'),                   # 5 거래처코드
        r.get('trNm'),                   # 6 거래처명
        r.get('trgrpCd'),                # 7 거래처분류코드
        r.get('trgrpNm'),                # 8 거래처분류명
        grp,                             # 9 적요구분 (0/1/2/3)
        r.get('baNb'),                   # 10 계좌번호
        r.get('bankNm'),                 # 11 금융기관
        r.get('depositor'),              # 12 예금주
        str(r.get('fillDt') or '') or None,  # 13 작성일 (raw YYYYMMDD)
        r.get('fillNb'),                 # 14 작성번호
        r.get('lnSq') or r.get('dispSq'),  # 15 분개순번
        r.get('fillNb'),                 # 16 승인번호 (= 작성번호 same)
        r.get('divCd'),                  # 17 회계단위코드
        r.get('divNm'),                  # 18 회계단위명
        r.get('deptCd'),                 # 19 부서코드
        r.get('deptNm'),                 # 20 부서명
        r.get('empCd'),                  # 21 사원코드
        r.get('empNm'),                  # 22 사원명
        r.get('acctCd'),                 # 23 계정과목코드
        r.get('acctNm'),                 # 24 계정과목명
        r.get('pjtCode'),                # 25 프로젝트코드
        r.get('pjtName'),                # 26 프로젝트명
        r.get('ctDept'),                 # 27 사용부서코드
        r.get('ctDeptNm'),               # 28 사용부서명
        r.get('mgmtEmpCd'),              # 29 관리사원코드
        r.get('mgmtEmpNm'),              # 30 관리사원명
    ]


def _acc3010_marker_row(rmk: str, dr: float, cr: float, balance: float,
                         tr: dict, grp: str) -> list:
    """Build a [전월이월] / [월계] / [누계] marker row."""
    row = [None] * 31
    row[1] = rmk           # 적요
    row[2] = dr            # 차변
    row[3] = cr            # 대변
    row[4] = balance       # 잔액
    row[5] = tr.get('trCd')
    row[6] = tr.get('trNm')
    row[7] = tr.get('trgrpCd')
    row[8] = tr.get('trgrpNm')
    row[9] = grp
    return row


def build_acc3010_xlsx(api_rows: list[dict], path: str | Path) -> tuple[int, dict]:
    """Build ACC3010 거래처원장 xlsx — transaction-level with running balance,
    [월계] per month, [누계] per accumulator, mirroring ERP UI Export.

    Input api_rows: output of acc3010_period_view() — each row is either
    a carry (rmkDc='[ 전 월 이 월 ]', grp='0') or a real transaction
    (grp='1' with fillDt set).
    """
    from collections import OrderedDict

    # Group rows by (trCd, acctCd), then within group by (year-month) for
    # 월계 / 누계 markers.
    grouped: OrderedDict = OrderedDict()
    for r in api_rows:
        tr = r.get('trCd')
        if not tr:
            continue
        grouped.setdefault(tr, []).append(r)

    out_rows: list[list] = [ACC3010_HEADER]
    for tr_cd, rows in grouped.items():
        # Sort: carry first, then transactions by fillDt+lnSq
        carry_rows = [r for r in rows if '이 월' in (r.get('rmkDc') or '')]
        tx_rows = [r for r in rows if '이 월' not in (r.get('rmkDc') or '')]
        tx_rows.sort(key=lambda r: (
            str(r.get('fillDt') or ''),
            str(r.get('fillNb') or ''),
            r.get('lnSq') or r.get('dispSq') or 0,
        ))

        sample = (carry_rows or tx_rows)[0] if (carry_rows or tx_rows) else {}
        running = 0.0
        cum_dr = cum_cr = 0.0  # cumulative since start of carry
        month_dr = month_cr = 0.0
        cur_month: Optional[str] = None

        # Emit carry first (no month marker before it)
        for cr_row in carry_rows:
            dr = cr_row.get('acctAmDr') or 0
            cr = cr_row.get('acctAmCr') or 0
            running += dr - cr
            cum_dr += dr
            cum_cr += cr
            out_rows.append(_acc3010_row(cr_row, running, grp='0'))

        # Walk transactions; emit 월계+누계 at month change
        for tx in tx_rows:
            fd = str(tx.get('fillDt') or '')
            ym = fd[:6] if len(fd) >= 6 else cur_month
            if cur_month and ym != cur_month and (month_dr or month_cr):
                # End previous month
                out_rows.append(_acc3010_marker_row(
                    '[ 월     계 ]', month_dr, month_cr, running, sample, '2'))
                out_rows.append(_acc3010_marker_row(
                    '[ 누     계 ]', cum_dr, cum_cr, running, sample, '3'))
                month_dr = month_cr = 0.0
            cur_month = ym
            dr = tx.get('acctAmDr') or 0
            cr = tx.get('acctAmCr') or 0
            running += dr - cr
            cum_dr += dr
            cum_cr += cr
            month_dr += dr
            month_cr += cr
            out_rows.append(_acc3010_row(tx, running, grp='1'))

        # Tail markers for last month / 누계
        if month_dr or month_cr or carry_rows or tx_rows:
            out_rows.append(_acc3010_marker_row(
                '[ 월     계 ]', month_dr, month_cr, running, sample, '2'))
            out_rows.append(_acc3010_marker_row(
                '[ 누     계 ]', cum_dr, cum_cr, running, sample, '3'))

    wb = Workbook()
    ws = wb.active
    ws.title = '거래처원장'
    for r in out_rows:
        ws.append(r)
    for c in ws[1]:
        c.font = Font(bold=True, color='FFFFFF')
        c.fill = PatternFill('solid', fgColor='305496')
        c.alignment = Alignment(horizontal='center', vertical='center')
    for col in ws.columns:
        w = max((len(str(c.value or '')) for c in col[:200]), default=10)
        ws.column_dimensions[col[0].column_letter].width = min(max(w + 2, 10), 40)
    ws.freeze_panes = 'A2'
    wb.save(path)

    return len(out_rows), {
        'data_rows': len(out_rows) - 1,
        '거래처': len(grouped),
    }


def build_acc3030_xlsx(api_rows: list[dict], path: str | Path) -> tuple[int, dict]:
    """Build ERP-styled ACC3030 xlsx from raw API rows. Returns (row_count, summary)."""
    rows = sorted(api_rows, key=_sort_key)

    # Group: trCd → acctCd → [rows] (preserve insertion order)
    groups: OrderedDict[str, OrderedDict[str, list]] = OrderedDict()
    for r in rows:
        tr, acct = r.get('trCd'), r.get('acctCd')
        if not (tr and acct):
            continue
        groups.setdefault(tr, OrderedDict()).setdefault(acct, []).append(r)

    out_rows: list[list] = [HEADER_36]
    grand_dr = grand_cr = 0.0
    for tr, accts in groups.items():
        first_row = next(iter(accts.values()))[0]
        attrNm = first_row.get('attrNm') or ''
        divCd = first_row.get('divCd') or ''
        divNm = first_row.get('divNm') or ''

        tr_dr = tr_cr = 0.0
        for acct, acct_rows in accts.items():
            acctNm = acct_rows[0].get('acctNm') or ''
            running = 0.0
            acct_dr = acct_cr = 0.0
            for i, r in enumerate(acct_rows):
                dr = r.get('drAm') or 0
                cr = r.get('crAm') or 0
                running += dr - cr
                out_rows.append(_data_row(r, first_in_group=(i == 0),
                                          running_balance=running,
                                          attrNm=attrNm, divCd=divCd, divNm=divNm))
                acct_dr += dr
                acct_cr += cr
            out_rows.append(_subtotal_row(acctNm, acct_dr, acct_cr))
            tr_dr += acct_dr
            tr_cr += acct_cr

        out_rows.append(_customer_total_row(attrNm, tr_dr, tr_cr))
        grand_dr += tr_dr
        grand_cr += tr_cr

    out_rows.append(_grand_total_row(grand_dr, grand_cr))

    # Write workbook
    wb = Workbook()
    ws = wb.active
    ws.title = '거래처계정내역'
    for r in out_rows:
        ws.append(r)
    for c in ws[1]:
        if c.value:
            c.font = Font(bold=True, color='FFFFFF')
            c.fill = PatternFill('solid', fgColor='305496')
            c.alignment = Alignment(horizontal='center', vertical='center')
    for col in ws.columns:
        w = max((len(str(c.value or '')) for c in col[:200]), default=10)
        ws.column_dimensions[col[0].column_letter].width = min(max(w + 2, 10), 40)
    ws.freeze_panes = 'A2'
    wb.save(path)

    return len(out_rows), {
        'data_rows': len(out_rows) - 1,
        'grand_dr': grand_dr,
        'grand_cr': grand_cr,
        'net_balance': grand_dr - grand_cr,
        '거래처': len(groups),
    }
